team4-GroupWare/grouopware-project

- src/main/java/com/mycompany/webapp/approval/model/Approval.java
> [#1] 지호 git 테스트

- src/main/webapp/resources/template3/approval_form.html
- src/main/webapp/resources/template3/assets/css/style.css
> 헤드 메뉴드롭바, 전자결재

- src/main/java/com/mycompany/webapp/HomeController.java
- src/main/java/com/mycompany/webapp/email/controller/EmailController.java
- src/main/webapp/resources/template3/approval_list.html
- src/main/webapp/resources/template3/email/email_complete.html
- src/main/webapp/resources/template3/email/email_list.html
- src/main/webapp/resources/template3/email/email_writeform.html
- src/main/webapp/resources/template3/email/receive_email_detail.html
- src/main/webapp/resources/template3/email/send_email_detail.html
- src/main/webapp/resources/template3/email/send_email_list.html
- src/main/webapp/resources/template3/user/login.html
> merge 및 로그인 로그 수정

- src/main/java/com/mycompany/webapp/employee/controller/EmployeeController.java
- src/main/java/com/mycompany/webapp/employee/model/Employee.java
- src/main/java/com/mycompany/webapp/employee/repository/IEmployeeRepositsory.java
- src/main/java/com/mycompany/webapp/employee/service/EmployeeService.java
- src/main/java/com/mycompany/webapp/employee/service/IEmployeeService.java
- src/main/webapp/resources/template3/approval_detail.html
- src/main/webapp/resources/template3/approval_list.html
> views 폴더 생성 및 Employee 폴더 생성

- src/main/java/com/mycompany/webapp/employee/model/Department.java
- src/main/java/com/mycompany/webapp/employee/model/Grade.java
- src/main/java/com/mycompany/webapp/employee/model/Team.java
> dept, grade, team 추가

- src/main/java/com/mycompany/webapp/group/controller/DepartmentController.java
- src/main/java/com/mycompany/webapp/group/service/DepartmentService.java
- src/main/java/com/mycompany/webapp/security.java
- src/main/resources/database/jdbc.properties
- src/main/resources/mybatis/mapper-config.xml
- src/main/resources/mybatis/mapper/department.xml
- src/main/resources/spring/datasource.xml
- src/main/resources/spring/mybatis.xml
- src/main/webapp/WEB-INF/views/hr/hr.jsp
- src/main/webapp/resources/approval_form.jsp
> department 연결 성공

- src/main/java/com/mycompany/webapp/group/controller/DepartmentController.java
- src/main/resources/log4j2.xml
- src/main/webapp/WEB-INF/views/common/footer.jsp
- src/main/webapp/WEB-INF/views/common/header.jsp
> 이미지 경로 재설정, log 설정

- src/main/webapp/WEB-INF/views/common/footer.jsp
- src/main/webapp/WEB-INF/views/common/header.jsp
> footer js 수정

- src/main/java/com/mycompany/webapp/interceptor/LoginInterceptor.java
- src/main/resources/mybatis/mapper/employee.xml
- src/main/resources/spring/interceptor.xml
- src/main/webapp/WEB-INF/views/employee/login.jsp
> #27 add login interceptor

- src/main/java/com/mycompany/webapp/employee/controller/EmployeeController.java
- src/main/java/com/mycompany/webapp/employee/repository/EmployeeRepository.java
- src/main/java/com/mycompany/webapp/employee/service/EmployeeService.java
- src/main/java/com/mycompany/webapp/employee/service/IEmployeeService.java
- src/main/java/com/mycompany/webapp/group/controller/GradeController.java
- src/main/java/com/mycompany/webapp/group/controller/GroupController.java
- src/main/java/com/mycompany/webapp/group/controller/TeamController.java
- src/main/java/com/mycompany/webapp/group/model/Department.java
- src/main/java/com/mycompany/webapp/group/repository/TeamRepository.java
- src/main/java/com/mycompany/webapp/group/service/ITeamService.java
- src/main/java/com/mycompany/webapp/group/service/TeamService.java
- src/main/resources/mybatis/mapper-config.xml
- src/main/resources/mybatis/mapper/department.xml
- src/main/resources/mybatis/mapper/employee.xml
- src/main/resources/mybatis/mapper/team.xml
- src/main/webapp/WEB-INF/views/hr/hr.jsp
> [#25] 조직도 사원목록 수정중

- pom.xml
- src/main/java/com/mycompany/webapp/employee/repository/EmployeeRepository.java
- src/main/java/com/mycompany/webapp/employee/service/EmployeeService.java
- src/main/java/com/mycompany/webapp/employee/service/IEmployeeService.java
- src/main/java/com/mycompany/webapp/group/controller/GroupController.java
- src/main/java/com/mycompany/webapp/interceptor/LoginInterceptor.java
- src/main/resources/mybatis/mapper/employee.xml
- src/main/webapp/WEB-INF/views/hr/hr.jsp
> maven 버전 변경

- src/main/java/com/mycompany/webapp/employee/controller/AlreadyExistingIdException.java
- src/main/java/com/mycompany/webapp/employee/controller/EmployeeController.java
- src/main/java/com/mycompany/webapp/employee/controller/NotExistingManagerException.java
- src/main/java/com/mycompany/webapp/employee/model/EmpValidator.java
- src/main/java/com/mycompany/webapp/employee/repository/EmployeeRepository.java
- src/main/java/com/mycompany/webapp/employee/service/EmployeeService.java
- src/main/java/com/mycompany/webapp/employee/service/IEmployeeService.java
- src/main/resources/mybatis/mapper/employee.xml
- src/main/resources/spring/component_scan.xml
- src/main/webapp/WEB-INF/views/employee/login.jsp
- src/main/webapp/WEB-INF/views/employee/register.jsp
- src/main/webapp/resources/assets/css/style.css
#26 유효성 검사에서 error 메세지가 나타나지 않고 있음..
> #26 유효성 검사 진행중

- src/main/java/com/mycompany/webapp/employee/controller/EmployeeController.java
- src/main/java/com/mycompany/webapp/employee/model/Employee.java
- src/main/java/com/mycompany/webapp/employee/repository/EmployeeRepository.java
- src/main/java/com/mycompany/webapp/employee/service/EmployeeService.java
- src/main/java/com/mycompany/webapp/employee/service/IEmployeeService.java
- src/main/java/com/mycompany/webapp/group/controller/GroupController.java
- src/main/resources/mybatis/mapper/employee.xml
- src/main/webapp/WEB-INF/views/common/footer.jsp
- src/main/webapp/WEB-INF/views/common/header.jsp
- src/main/webapp/WEB-INF/views/hr/hr2.jsp
> [#25] 조직도 페이징 완료

- src/main/java/com/mycompany/webapp/employee/controller/EmployeeController.java
- src/main/resources/mybatis/mapper/employee.xml
- src/main/webapp/WEB-INF/views/common/header.jsp
- src/main/webapp/WEB-INF/views/employee/register.jsp
> #39 유효성검사, 로그아웃, head에 회원정보

- pom.xml
- src/main/java/com/mycompany/webapp/employee/controller/EmployeeController.java
- src/main/java/com/mycompany/webapp/employee/model/EmpValidator.java
- src/main/webapp/WEB-INF/views/employee/register.jsp
> #39 회원가입 완료

- src/main/java/com/mycompany/webapp/email/controller/EmailController.java
- src/main/java/com/mycompany/webapp/email/model/EmailContent.java
- src/main/java/com/mycompany/webapp/email/model/EmailList.java
- src/main/java/com/mycompany/webapp/email/model/ReceiveEmail.java
- src/main/java/com/mycompany/webapp/email/model/SendEmail.java
- src/main/java/com/mycompany/webapp/email/repository/EmailRepository.java
- src/main/java/com/mycompany/webapp/email/service/EmailService.java
- src/main/java/com/mycompany/webapp/email/service/IEmailService.java
- src/main/resources/mybatis/mapper/email.xml
- src/main/webapp/WEB-INF/views/common/header.jsp
- src/main/webapp/WEB-INF/views/email/complete.jsp
- src/main/webapp/WEB-INF/views/email/emaillist.jsp
- src/main/webapp/WEB-INF/views/email/receivedetail.jsp
- src/main/webapp/WEB-INF/views/email/senddetail.jsp
- src/main/webapp/WEB-INF/views/email/sendlist.jsp
- src/main/webapp/WEB-INF/views/email/write.jsp
> #56 보낸메일, 받은 메일 mail list

- src/main/webapp/WEB-INF/views/email/emaillist.jsp
- src/main/webapp/WEB-INF/views/email/sendlist.jsp
#57 email 네비게이터, email 목록 없을 때 수정  
받은 메일, 보낸 메일
> #57 email 네비게이터, email 목록 없을 때 수정 (받은 메일, 보낸 메일)

- src/main/java/com/mycompany/webapp/employee/controller/EmployeeController.java
- src/main/java/com/mycompany/webapp/filter/LoginFilter.java
- src/main/java/com/mycompany/webapp/interceptor/LoginInterceptor.java
- src/main/resources/spring/interceptor.xml
- src/main/webapp/WEB-INF/views/employee/login.jsp
- src/main/webapp/WEB-INF/web.xml
> #26 loginInterceptor 기능 수정 완료

- src/main/java/com/mycompany/webapp/employee/controller/EmployeeController.java
> #26 권한 어노테이션 삭제

- src/main/resources/spring/interceptor.xml
> #26 loginInterceptor 경로 수정

- pom.xml
- src/main/java/com/mycompany/webapp/approval/controller/ApprovalController.java
- src/main/java/com/mycompany/webapp/approval/repository/ApprovalRepository.java
- src/main/java/com/mycompany/webapp/approval/repository/IApprovalRepository.java
- src/main/java/com/mycompany/webapp/approval/service/ApprovalService.java
- src/main/java/com/mycompany/webapp/approval/service/IApprovalService.java
- src/main/resources/mybatis/mapper-config.xml
- src/main/resources/mybatis/mapper/approval.xml
- src/main/resources/spring/mybatis.xml
- src/main/webapp/WEB-INF/views/approval/approval_form.jsp
- src/main/webapp/resources/test.jsp
[#48] 전자결재 작성 진행중
- 카테고리 목록 조회 성공
> [#48] 전자결재 작성 진행중

- src/main/java/com/mycompany/webapp/email/controller/EmailController.java
- src/main/java/com/mycompany/webapp/email/repository/EmailRepository.java
- src/main/java/com/mycompany/webapp/email/service/EmailService.java
- src/main/java/com/mycompany/webapp/email/service/IEmailService.java
- src/main/resources/mybatis/mapper/email.xml
- src/main/webapp/WEB-INF/views/email/emaillist.jsp
- src/main/webapp/WEB-INF/views/email/sendlist.jsp
> #70 메일 리스트에서 삭제 및 영구삭제 구현

- src/main/webapp/WEB-INF/views/email/emaillist.jsp
> #71 목록에서 삭제

- src/main/java/com/mycompany/webapp/approval/controller/ApprovalController.java
- src/main/java/com/mycompany/webapp/approval/service/ApprovalService.java
- src/main/java/com/mycompany/webapp/approval/service/IApprovalService.java
- src/main/webapp/WEB-INF/views/approval/approval_form.jsp
- src/main/webapp/WEB-INF/views/vacation/form_modal.jsp
> [#48] 결제선 선택 모달 수정

- src/main/java/com/mycompany/webapp/email/controller/EmailController.java
- src/main/java/com/mycompany/webapp/email/model/EmailDetail.java
- src/main/java/com/mycompany/webapp/email/repository/EmailRepository.java
- src/main/java/com/mycompany/webapp/email/service/EmailService.java
- src/main/java/com/mycompany/webapp/email/service/IEmailService.java
- src/main/java/com/mycompany/webapp/employee/controller/EmployeeController.java
- src/main/java/com/mycompany/webapp/employee/service/EmployeeService.java
- src/main/resources/mybatis/mapper-config.xml
- src/main/resources/mybatis/mapper/email.xml
- src/main/webapp/WEB-INF/views/email/complete.jsp
- src/main/webapp/WEB-INF/views/email/emaillist.jsp
- src/main/webapp/WEB-INF/views/email/sendlist.jsp
- src/main/webapp/WEB-INF/views/email/write.jsp
> #70 #76 #82 메일 삭제, 복구, 쓰기 초안

- src/main/webapp/WEB-INF/views/approval/approval_list.jsp
- src/main/webapp/WEB-INF/views/main.jsp
- src/main/webapp/resources/assets/css/style.css
- src/main/webapp/resources/assets/js/schedule.js
메인 화면 아이콘 호버 및 캘린더 수정
글꼴 수정
전자결재 리스트 마우스 모양 변경
> 메인 화면 아이콘 호버 및 캘린더 수정

- src/main/java/com/mycompany/webapp/email/controller/EmailController.java
- src/main/java/com/mycompany/webapp/email/repository/EmailRepository.java
- src/main/java/com/mycompany/webapp/email/service/EmailService.java
- src/main/java/com/mycompany/webapp/email/service/IEmailService.java
- src/main/java/com/mycompany/webapp/employee/controller/EmployeeController.java
- src/main/java/com/mycompany/webapp/employee/repository/EmployeeRepository.java
- src/main/java/com/mycompany/webapp/employee/service/EmployeeService.java
- src/main/java/com/mycompany/webapp/employee/service/IEmployeeService.java
- src/main/resources/mybatis/mapper/email.xml
- src/main/resources/mybatis/mapper/employee.xml
- src/main/webapp/WEB-INF/views/email/emaillist.jsp
- src/main/webapp/WEB-INF/views/email/receivedetail.jsp
- src/main/webapp/WEB-INF/views/email/senddetail.jsp
- src/main/webapp/WEB-INF/views/email/sendlist.jsp
- src/main/webapp/WEB-INF/views/employee/user_profileupdate.jsp
> #91 #89 휴대폰번호 변경, 메일 상세 구현

- src/main/java/com/mycompany/webapp/approval/controller/ApprovalController.java
- src/main/java/com/mycompany/webapp/approval/model/Approval.java
- src/main/java/com/mycompany/webapp/approval/model/ApprovalLine.java
- src/main/java/com/mycompany/webapp/employee/model/Employee.java
- src/main/webapp/WEB-INF/views/approval/approval_form.jsp
- src/main/webapp/WEB-INF/views/common/header.jsp
- src/main/webapp/WEB-INF/views/vacation/form_modal.jsp
> [#48] 전자결재 작성 결재선 순서대로 출력

- src/main/java/com/mycompany/webapp/approval/controller/ApprovalController.java
- src/main/java/com/mycompany/webapp/approval/repository/ApprovalRepository.java
- src/main/java/com/mycompany/webapp/approval/service/ApprovalService.java
- src/main/java/com/mycompany/webapp/approval/service/IApprovalService.java
- src/main/java/com/mycompany/webapp/employee/model/Employee.java
- src/main/java/com/mycompany/webapp/employee/service/EmployeeService.java
- src/main/resources/mybatis/mapper-config.xml
- src/main/resources/mybatis/mapper/approval.xml
- src/main/webapp/WEB-INF/views/approval/approval_detail.jsp
- src/main/webapp/WEB-INF/views/approval/approval_form.jsp
- src/main/webapp/WEB-INF/views/approval/approval_list.jsp
- src/main/webapp/WEB-INF/views/approval/approval_templist.jsp
- src/main/webapp/WEB-INF/views/vacation/form_modal.jsp
> [#48] 전자결재 결재선 수정

- src/main/java/com/mycompany/webapp/email/MultipartFileResolver.java
- src/main/java/com/mycompany/webapp/email/controller/EmailController.java
- src/main/java/com/mycompany/webapp/email/model/EmailDetail.java
- src/main/java/com/mycompany/webapp/email/model/EmailFile.java
- src/main/java/com/mycompany/webapp/email/repository/EmailFileRepository.java
- src/main/java/com/mycompany/webapp/email/service/EmailService.java
- src/main/java/com/mycompany/webapp/email/service/IEmailService.java
- src/main/resources/mybatis/mapper-config.xml
- src/main/resources/mybatis/mapper/emailfile.xml
- src/main/webapp/WEB-INF/views/email/complete.jsp
- src/main/webapp/WEB-INF/views/email/emaillist.jsp
- src/main/webapp/WEB-INF/views/email/receivedetail.jsp
- src/main/webapp/WEB-INF/views/email/senddetail.jsp
- src/main/webapp/WEB-INF/views/email/sendlist.jsp
- src/main/webapp/WEB-INF/views/email/write.jsp
- src/main/webapp/WEB-INF/views/employee/grantpassword.jsp
- src/main/webapp/resources/assets/css/style.css
- src/main/webapp/resources/grantpassword.jsp
> #56 메일 리스트 뷰 수정

- src/main/webapp/WEB-INF/views/email/senddetail.jsp
- src/main/webapp/resources/assets/css/style.css
- src/main/webapp/resources/assets/js/file.js
> #112 파일box css 수정,  보낸 메일 삭제 수정

- src/main/java/com/mycompany/webapp/email/controller/EmailController.java
- src/main/java/com/mycompany/webapp/email/model/EmailDetail.java
- src/main/java/com/mycompany/webapp/email/repository/EmailRepository.java
- src/main/java/com/mycompany/webapp/email/service/EmailService.java
- src/main/resources/mybatis/mapper/email.xml
- src/main/resources/mybatis/mapper/emailfile.xml
- src/main/webapp/WEB-INF/views/email/write.jsp
- src/main/webapp/resources/assets/css/style.css
- src/main/webapp/resources/assets/js/file.js
> #112 메일 파일 업로드

- src/main/java/com/mycompany/webapp/employee/controller/EmployeeController.java
- src/main/webapp/WEB-INF/views/hr/hr.jsp
> [#25] 조직도 사원 상세보기 프로필이미지 추가

- src/main/java/com/mycompany/webapp/employee/controller/EmployeeController.java
- src/main/webapp/WEB-INF/views/board/boardlist.jsp
> 초기 비밀번호 변경 설정

- src/main/java/com/mycompany/webapp/employee/service/EmployeeService.java
- src/main/java/com/mycompany/webapp/group/controller/GroupController.java
- src/main/webapp/WEB-INF/views/hr/hr.jsp
- src/main/webapp/WEB-INF/views/hr/hrmain.jsp
> [#25] 조직도 사이드바 추가 및 이미지크기 수정

- src/main/java/com/mycompany/webapp/approval/service/IApprovalService.java
- src/main/java/com/mycompany/webapp/noticeboard/controller/NoticeBoardController.java
- src/main/java/com/mycompany/webapp/noticeboard/model/NoticeBoard.java
- src/main/java/com/mycompany/webapp/noticeboard/model/NoticeFile.java
- src/main/java/com/mycompany/webapp/noticeboard/repositiorty/NoticeBoardRepository.java
- src/main/java/com/mycompany/webapp/noticeboard/service/INoticeBoardService.java
- src/main/java/com/mycompany/webapp/noticeboard/service/NoticeBoardService.java
- src/main/resources/mybatis/mapper-config.xml
- src/main/resources/mybatis/mapper/employee.xml
- src/main/resources/mybatis/mapper/noticeboard.xml
- src/main/resources/spring/mybatis.xml
- src/main/webapp/WEB-INF/views/approval/approval_confirmlist.jsp
- src/main/webapp/WEB-INF/views/approval/approval_mylist.jsp
- src/main/webapp/WEB-INF/views/approval/approvalform_modal.jsp
- src/main/webapp/WEB-INF/views/board/boarddetail.jsp
- src/main/webapp/WEB-INF/views/board/boardlist.jsp
- src/main/webapp/WEB-INF/views/board/main_boardlist.jsp
- src/main/webapp/WEB-INF/views/board/write.jsp
- src/main/webapp/WEB-INF/views/common/header.jsp
- src/main/webapp/WEB-INF/views/main.jsp
- src/main/webapp/WEB-INF/views/vacation/form_modal.jsp
[#147], [#148], [#149] 공지사항 기능
> [#147], [#148], [#149] 공지사항 기능

- src/main/java/com/mycompany/webapp/employee/controller/EmployeeController.java
> #114 인사팀이 자기자신 정보 수정

- src/main/java/com/mycompany/webapp/group/controller/GroupController.java
- src/main/java/com/mycompany/webapp/noticeboard/controller/NoticeBoardController.java
- src/main/resources/mybatis/mapper/noticeboard.xml
- src/main/resources/spring/interceptor.xml
- src/main/webapp/WEB-INF/views/approval/approval_confirmlist.jsp
- src/main/webapp/WEB-INF/views/approval/approval_mylist.jsp
- src/main/webapp/WEB-INF/views/approval/approval_reflist.jsp
- src/main/webapp/WEB-INF/views/approval/approval_templist.jsp
- src/main/webapp/WEB-INF/views/approval/approval_writeform.jsp
- src/main/webapp/WEB-INF/views/board/boarddetail.jsp
- src/main/webapp/WEB-INF/views/board/boardlist.jsp
- src/main/webapp/WEB-INF/views/employee/login.jsp
- src/main/webapp/WEB-INF/views/hr/hrmain.jsp
- src/main/webapp/WEB-INF/views/main.jsp
> [#148] 메인 공지사항 수정

- src/main/webapp/WEB-INF/views/board/main_boardlist.jsp
> 메인 공지사항 수정

- src/main/java/com/mycompany/webapp/approval/controller/ApprovalController.java
- src/main/java/com/mycompany/webapp/component/AttendanceScheduler.java
- src/main/webapp/WEB-INF/views/approval/approval_confirmlist.jsp
- src/main/webapp/WEB-INF/views/approval/approval_detail.jsp
- src/main/webapp/WEB-INF/views/approval/approval_mylist.jsp
- src/main/webapp/WEB-INF/views/approval/approval_reflist.jsp
- src/main/webapp/WEB-INF/views/approval/approval_tempform.jsp
- src/main/webapp/WEB-INF/views/approval/approval_templist.jsp
- src/main/webapp/WEB-INF/views/approval/approval_writeform.jsp
- src/main/webapp/WEB-INF/views/board/main_boardlist.jsp
- src/main/webapp/WEB-INF/views/email/mainemaillist.jsp
- src/main/webapp/WEB-INF/views/email/mainreceiveemaillist.jsp
- src/main/webapp/WEB-INF/views/hr/hrmain.jsp
> 리스트 제목 글자수 제한

- src/main/webapp/WEB-INF/views/email/emaillist.jsp
> #77 휴지통 메일 복구 수정

- src/main/java/com/mycompany/webapp/approval/controller/ApprovalController.java
- src/main/webapp/WEB-INF/views/approval/approval_tempform.jsp
> [#129] 임시저장 제출 오류수정

- src/main/java/com/mycompany/webapp/employee/controller/EmployeeController.java
> #39 기본값 적용

- src/main/webapp/WEB-INF/views/overtime/overtime_detail.jsp
- src/main/webapp/WEB-INF/views/vacation/vacation_detail.jsp
> 승인 날짜 -> 결재날짜로 고침

- src/main/webapp/WEB-INF/views/email/temp.jsp
- src/main/webapp/WEB-INF/views/email/write.jsp
> #98 임시저장 체크 오류 수정
